---
- name: Check Docker
  command: docker --version
  changed_when: false
  failed_when: false

- name: Check Docker plugin 
  command: docker compose version
  register: docker_compose_version
  changed_when: false
  failed_when: false

- name: Download Docker installaton script
  get_url: 
    url: "{{ docker_install_script_url }}"
    dest: "{{ docker_install_script_path }}"
    owner: root
    group: root
    mode: "0700"
  when: docker_version.rc != 0 or docker_compose_version.rc != 0

- name: Install Docker and compose
  command: 
    cmd: "sh {{ docker_install_script_path }}"
  when: docker_version.rc != 0 or docker_compose_version.rc != 0

- name: Remove Docker installaton script
  file: 
  path: "{{ docker_install_script_path }}"
  stage: absent

- name: Enable and start Docker
  service: 
    name: docker
    enabled: true
    state: started

- name: Add administrative user to docker group 
  user: 
    name: "{{ admib_user }}"
    groups: docker
    append: true

- name: Verify Docker compose plugin
  command: docker compose version 
  changed_when: false


  