---
- name: Install base packages
  import_tasks: packages.yml

- name: Configure system 
  import_tasks: system.yml

- name: Configure user
  import_tasks: user.yml

- name: Install Docker
  import_tasks: docker.yml
  

